# Generated by Django 2.1.5 on 2021-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='project11',
        ),
    ]
