# Generated by Django 2.1.5 on 2021-11-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='images',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
